version: '3'

services:

  db:
    image: postgres:latest
    container_name: postgres-TaxiStop
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_DB: TaxiStop
    ports:
      - "5432:5432"
    #volumes:
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql